language: node_js
node_js:
- node
notifications:
  email: false
addons:
  ssh_known_hosts:
  - github.com
  - 104.131.105.95
before_deploy:
- openssl aes-256-cbc -K $encrypted_1495c74e237e_key -iv $encrypted_1495c74e237e_iv -in deploy_key.pem.enc -out deploy_key.pem -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key.pem
- ssh-add deploy_key.pem
script:
- echo 'No tests'
deploy:
  provider: script
  script: git remote add dokku dokku@104.131.105.95:devschile.cl && git push dokku master
  skip_cleanup: true
  on:
    branch: master
