language: node_js
node_js:
- node
notifications:
  email: false
addons:
  ssh_known_hosts:
  - github.com
  - 104.131.105.95
before_install:
- cd public
install:
- npm install -g bower
- npm install
- bower install
before_deploy:
- grunt
- cd ..
- openssl aes-256-cbc -K $encrypted_1495c74e237e_key -iv $encrypted_1495c74e237e_iv -in deploy_key.pem.enc -out deploy_key.pem -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key.pem
- ssh-add deploy_key.pem
deploy:
  skip_cleanup: true
  provider: script
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public/dist/. static@104.131.105.95:~/sites/devschile.cl
  on:
    branch: master
